[package]
name = "agy-auth-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
repository.workspace = true
license.workspace = true
build = "build.rs"

[features]
experimental-profile-credentials = []

[dependencies]
agy-auth-domain.workspace = true
serde.workspace = true
time.workspace = true

[lints]
workspace = true
